language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script: echo "Running Continous Integration.."

jobs:
  include:
    - stage: "Unit Test"
      name: "Unit test component react"
      script: yarn test -u
    - stage: "Coverage Test Result"
      name: "Report unit test to coveralls"
      script:
        - yarn run test-coverage
        - yarn run test-coverage -u
    - stage: "Build"
      name: "Build the app"
      script: yarn run build